# Generated by Django 3.0.5 on 2020-06-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_auto_20200608_1219'),
        ('gardens', '0007_auto_20200608_1005'),
    ]

    operations = [
    ]
