# Generated by Django 3.0.5 on 2020-06-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0009_merge_20200608_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=29),
        ),
    ]
