# Generated by Django 3.0.5 on 2020-06-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='temperature',
            field=models.IntegerField(default=20),
        ),
    ]
