# Generated by Django 3.0.5 on 2020-06-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_manuring_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='manuring_date',
            new_name='last_cutting_date',
        ),
        migrations.AddField(
            model_name='plant',
            name='cutting_frequency_byDays',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_manuring_date',
            field=models.DateField(default='2000-11-11'),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watering_date',
            field=models.DateField(default='2000-11-11'),
        ),
        migrations.AddField(
            model_name='plant',
            name='manuring_frequency_byDays',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency_byDays',
            field=models.IntegerField(default=3),
        ),
    ]
