# Generated by Django 3.0.5 on 2020-06-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_auto_20200609_2124'),
        ('plants', '0005_nvm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nvm',
            new_name='Garden_Plants',
        ),
    ]
