# Generated by Django 3.0.5 on 2020-06-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_auto_20200609_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='Garden',
        ),
    ]
