# Generated by Django 3.0.5 on 2020-06-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_auto_20200609_2124'),
        ('plants', '0007_remove_plant_garden'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garden_Plants',
            new_name='associativeGarden',
        ),
    ]
