# Generated by Django 3.0.5 on 2020-06-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_auto_20200609_2124'),
        ('plants', '0009_auto_20200609_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='associative_Garden',
            new_name='associative_Gardens',
        ),
    ]
