# Generated by Django 3.0.5 on 2020-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0010_auto_20200609_2124'),
        ('plants', '0010_auto_20200609_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associative_gardens',
            name='id_garden',
            field=models.ForeignKey(on_delete=models.SET(0), to='gardens.Garden'),
        ),
        migrations.AlterField(
            model_name='associative_gardens',
            name='id_plant',
            field=models.ForeignKey(on_delete=models.SET(0), to='plants.Plant'),
        ),
    ]
