# Generated by Django 3.0.4 on 2020-06-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_auto_20200612_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_name',
            field=models.CharField(default='brak_obrazka.jpg', max_length=100),
        ),
    ]
