# Generated by Django 3.0.5 on 2020-06-12 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_plant_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_cutting_date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_manuring_date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_watering_date',
            field=models.DateField(default=datetime.date(2020, 6, 13)),
        ),
    ]
