# Generated by Django 3.0.5 on 2020-06-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20200613_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_cutting_date',
            field=models.DateField(default='2000-11-11'),
        ),
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_manuring_date',
            field=models.DateField(default='2000-11-11'),
        ),
        migrations.AlterField(
            model_name='associative_gardens',
            name='last_watering_date',
            field=models.DateField(default='2000-11-11'),
        ),
    ]
