# Generated by Django 3.0.4 on 2020-06-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20200613_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image_name',
            field=models.CharField(default='brak_obrazka.png', max_length=100),
        ),
    ]
